# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: indexer
contracts:
- name: YeetFinance
  handler: src/EventHandlers.ts
  events:
  - event: CurveInitialized(address indexed dev, address indexed token, string name, string symbol, string description, string image, string twitter, string telegram, string website, uint256 kickoff)
  - event: TokenBought(address indexed trader, address indexed token, uint256 amount, uint256 ethIn)
  - event: TokenSold(address indexed trader, address indexed token, uint256 amount, uint256 ethOut)
networks:
- id: 84532
  start_block: 0
  contracts:
  - name: YeetFinance
    address:
    - 0x2D2Fd1C08865eAAcb930b7F31a46e42Bb7742A05
- id: 1313161555
  rpc_config:
    url: https://testnet.aurora.dev
  start_block: 178135282
  contracts:
  - name: YeetFinance
    address:
    - 0xEc87C5619A31665100e3d4d588f1a8B2a20275C0
field_selection:
  transaction_fields:
    - "hash"
rollback_on_reorg: false
